config/routes.rb
Comps::Application.routes.draw do
  resources :companies, :only => [:index]

  root to: "companies#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :earnings_cy, :earnings_cy_plus_one, :earnings_ltm, :enterprise_value, :market_cap, :name, :sales_cy, :sales_cy_plus_one, :sales_ltm, :ticker, :low_sales_cy, :high_sales_cy, :low_sales_cy_plus_one, :high_sales_cy_plus_one, :low_earnings_cy, :high_earnings_cy, :low_earnings_cy_plus_one, :high_earnings_cy_plus_one, :ev_ebitda, :stock_price, :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    @saas_companies = Company.where(:group=>"Software-as-a-Service").order("market_cap DESC")
    @ecommerce_companies = Company.where(:group=>"eCommerce").order("market_cap DESC")
    @online_retail_companies = Company.where(:group=>"Online Retail").order("market_cap DESC")
    @advertising_tech_companies = Company.where(:group=>"Advertising Tech").order("market_cap DESC")
    @content_companies = Company.where(:group=>"Content").order("market_cap DESC")
    @digital_media_companies = Company.where(:group=>"Digital Media").order("market_cap DESC")
    @gaming_companies = Company.where(:group=>"Gaming").order("market_cap DESC")
    @mobile_companies = Company.where(:group=>"Mobile").order("market_cap DESC")
    @web_services_companies = Company.where(:group=>"Web Services").order("market_cap DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ticker %><br />
    <%= f.text_field :ticker %>
  </div>
  <div class="field">
    <%= f.label :market_cap %><br />
    <%= f.text_field :market_cap %>
  </div>
  <div class="field">
    <%= f.label :enterprise_value %><br />
    <%= f.text_field :enterprise_value %>
  </div>
  <div class="field">
    <%= f.label :sales_ltm %><br />
    <%= f.text_field :sales_ltm %>
  </div>
  <div class="field">
    <%= f.label :sales_cy %><br />
    <%= f.text_field :sales_cy %>
  </div>
  <div class="field">
    <%= f.label :sales_cy_plus_one %><br />
    <%= f.text_field :sales_cy_plus_one %>
  </div>
  <div class="field">
    <%= f.label :earnings_ltm %><br />
    <%= f.text_field :earnings_ltm %>
  </div>
  <div class="field">
    <%= f.label :earnings_cy %><br />
    <%= f.text_field :earnings_cy %>
  </div>
  <div class="field">
    <%= f.label :earnings_cy_plus_one %><br />
    <%= f.text_field :earnings_cy_plus_one %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/_table.erb
<table class="table table-hover">
          <tr>
            <th>Company</th>
            <th>Ticker</th>
            <th>Share Price</th>
            <th>Market Cap</th>
            <th>Enterprise Value</th>
            <th>EV/CY Sales</th>
            <th>EV/CY+1 Sales</th>
            <th>EV/LTM EBITDA</th>
            <th>P/E CY</th>
          </tr>

        <% @company_group.each do |company| %>
          <% if !company.name.blank? %>
          <tr>
            <td><%= company.name %></td>
            <td><%= company.ticker %></td>
            <td>
                <% if !company.stock_price.nil? %>
                    <%= number_to_currency(company.stock_price) %>
                    <% else %>
                    <%= "na" %></td>
                <% end %>
            <td>
                <% if !company.market_cap.nil? %>
                    <%= number_to_currency(company.market_cap, :precision=>0) %>
                    <% else %>
                    <%= "na" %>
                <% end %></td>
            <td>
                <% if !company.enterprise_value.nil? %>
                    <% if company.enterprise_value < 0 %>
                        <%= "nmf" %>
                        <% else %>
                        <%= number_to_currency(company.enterprise_value, :precision=>0) %>
                    <% end %>
                <% else %>
                    <%= "na" %></td>
                <% end %>
            <td>
                <% if !company.sales_cy.nil? && !company.enterprise_value.nil? %>
                    <% if company.enterprise_value/(company.sales_cy) < 0 || company.enterprise_value/(company.sales_cy) > 100 %>
                        <%= "nmf" %>
                        <% else %>
                    <%= number_with_precision(company.enterprise_value/(company.sales_cy), :precision=>2) %>x
                    <% end %>
                <% else %>
                    <%= "na" %></td>
                <% end %>
            <td><% if !company.enterprise_value.nil? && !company.sales_cy_plus_one.nil? %>
                    <% if company.enterprise_value/(company.sales_cy_plus_one) < 0 || company.enterprise_value/(company.sales_cy_plus_one) > 100 %>
                        <%= "nmf" %>
                        <% else %>    
                    <%= number_with_precision(company.enterprise_value/(company.sales_cy_plus_one), :precision=>2) %>x
                    <% end %>
                <% else %>
                    <%= "na" %></td>
                <% end %>
            <td><% if !company.ev_ebitda.nil? %>
                    <% if company.ev_ebitda < 0 || company.ev_ebitda > 100 || company.ev_ebitda == 0 %>
                        <%= "nmf" %>
                        <% else %>
                        <%= number_with_precision(company.ev_ebitda, :precision=>1) %>x
                        <% end %>
                <% else %>
                    <%= "na" %></td>
                <% end %>
            <td><% if !company.stock_price.nil? && !company.earnings_ltm.nil? %>
                    <% if company.stock_price/(company.earnings_ltm) < 0 || company.stock_price/(company.earnings_ltm) > 100 %>
                    <%= "nmf" %>
                    <% else %>
                    <%= number_with_precision(company.stock_price/(company.earnings_ltm), :precision=>1) %>x
                    <% end %>
                <% else %>
                    <%= "na" %></td>
                <% end %>
            </tr>
            <% end %>
           <% end %> 
</table>

<p><small><i>Note: $ in millions except for share price; data from Yahoo! Finance.</i></small></p>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">Advertising Tech</a></li>
    <li><a href="#tab2" data-toggle="tab">Content</a></li>
    <li><a href="#tab3" data-toggle="tab">Digital Media</a></li>
    <li><a href="#tab4" data-toggle="tab">eCommerce</a></li>
    <li><a href="#tab5" data-toggle="tab">Gaming</a></li>
    <li><a href="#tab6" data-toggle="tab">Mobile</a></li>
    <li><a href="#tab7" data-toggle="tab">Online Retail</a></li>
    <li><a href="#tab8" data-toggle="tab">SaaS</a></li>
    <li><a href="#tab9" data-toggle="tab">Web Services</a></li>
  </ul>

  <div class="tab-content">

    
    <div class="tab-pane active" id="tab1">
        <h4>Advertising Tech</h4>
        <% @company_group = @advertising_tech_companies %>
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab2">
        <h4>Content</h4>
        <% @company_group = @content_companies %>
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab3">
        <h4>Digital Media</h4>
        <% @company_group = @digital_media_companies %>
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab4">
        <h4>eCommerce</h4>
        <% @company_group = @ecommerce_companies %>
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab5">
        <h4>Gaming</h4>
        <% @company_group = @gaming_companies %>
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab6">
        <h4>Mobile</h4>
        <% @company_group = @mobile_companies %>
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab7">
        <h4>Online Retail</h4>
        <% @company_group = @online_retail_companies %>
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab8">
        <h4>Software-as-a-Service</h4>
        <% @company_group = @saas_companies %>  
        <%= render 'companies/table' %>
    </div>

    <div class="tab-pane" id="tab9">
        <h4>Web Services</h4>
        <% @company_group = @web_services_companies %>  
        <%= render 'companies/table' %>
    </div>

    </div>
</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Ticker:</b>
  <%= @company.ticker %>
</p>

<p>
  <b>Market cap:</b>
  <%= @company.market_cap %>
</p>

<p>
  <b>Enterprise value:</b>
  <%= @company.enterprise_value %>
</p>

<p>
  <b>Sales ltm:</b>
  <%= @company.sales_ltm %>
</p>

<p>
  <b>Sales cy:</b>
  <%= @company.sales_cy %>
</p>

<p>
  <b>Sales cy plus one:</b>
  <%= @company.sales_cy_plus_one %>
</p>

<p>
  <b>Earnings ltm:</b>
  <%= @company.earnings_ltm %>
</p>

<p>
  <b>Earnings cy:</b>
  <%= @company.earnings_cy %>
</p>

<p>
  <b>Earnings cy plus one:</b>
  <%= @company.earnings_cy_plus_one %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "PublicTradingComps", root_path, :class => 'brand' %>
<ul class="nav">
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "comps" %></title>
    <meta name="public comparable company analysis" content="">
    <meta name="pat vihtelic" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div class="holder">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer class="footer">
            <div class="navbar navbar-fixed-bottom">
              <ul class="footer-nav">
                <li class="footer-nav"><%= link_to "Created by Pat Vihtelic", "http://www.linkedin.com/pub/patrick-vihtelic/6/b2b/a64", :class=>"footer-nav" %></li>
              </ul>
            </div>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    </div>
  </body>
</html>